---
title: "A Report Generated by R Markdown"
subtitle: "An Introduction to R Markdown"
author: "Prepared by: Isabel Li"
output: 
  officedown::rdocx_document:
    reference_docx: "template.docx"
  prettydoc::html_pretty:
      toc: true
      theme: cayman
date: "`r paste0('Reported Date: ', Sys.Date(), '   |   Data Extracted Date: ', params$data_extract_date, '   |   Data Cut-off Date: ', params$cutoff_date)`"
editor_options: 
  chunk_output_type: console
params:
  as_gt: true
  cutoff_date: "2025-08-15"
  data_extract_date: "2025-08-15"
  last_cutoff_date: "2025-03-24"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

```{css, echo=FALSE}
tr:hover {background-color: coral;}
```

```{r}
# source parameters and utility functions
source("src/parameters.R")

source("src/utils.R")

# set font defaults
flextable::set_flextable_defaults(font.family = "Cambria", font.size = 9)
```


# Data Summary
## second 
### third
```{r data_summary, tab.cap="Baseline Demographics and Clinical Characteristics"}
# create a simulated dataframe

set.seed(123)
n = 2000
data <- tibble(
  id = 1:n,
  age = sample(20:80, n, replace = TRUE),
  sex = sample(c("Male", "Female"), n, replace = TRUE),
  ecog = sample(0:4, n, replace = TRUE),
  race = sample(1:4, n, replace = TRUE),
  n_stage = sample(c("N0", "N1", "N2", "N3"), n, replace = TRUE),
  t_stage = sample(c("T1", "T2", "T3", "T4"), n, replace = TRUE), 
  blood_pressure = runif(n, min = 50, max = 190)
) %>% 
  dplyr::mutate(
    blood_pressure = blood_pressure + age *0.7,
    history_of_bp = ifelse(blood_pressure > 130, 1, 0))

# Assign variable labels using my predefined list
labelled::var_label(data) <- var_label_list

# gtsummary table
gtsummary::tbl_summary(
  data, 
  include = -"id",
  by = "sex"
) %>% 
  gtsummary::modify_header(label = "") %>% 
  gtsummary::modify_spanning_header(all_stat_cols() ~ "**Evaluable Patients**") %>% 
  gtsummary::bold_labels() %>% 
  gt_flex_transform(params$as_gt)

```

# Data Listing

```{r, tab.cap="Participant Data Listing"}
if(params$as_gt) {
  to_display <- data %>%
    dplyr::slice_head(n = 100) %>% 
    dplyr::mutate(across(where(labelled::is.labelled), ~ to_factor(.))) 
  
  DT::datatable(
  to_display,
  colnames = dt_colnames_from_labels(to_display),
  options = list(pageLength = 20, autoWidth = TRUE),
  rownames = FALSE,
  caption = htmltools::tags$caption(
    style = 'caption-side: bottom; text-align: left;',
    'Table 1: ', htmltools::em('Participant Data Listing')
  )
) %>%
  DT::formatStyle(
    'age',
    backgroundColor = DT::styleInterval(c(30, 50, 70), c('lightblue', 'lightgreen', 'yellow', 'orange'))
  )
}
```

```{r, tab.cap="Participant Data Listing"}
if(!params$as_gt) {
# create flextable
ft <- data %>% 
  dplyr::slice_head(n = 100) %>% 
  flextable() %>%
  set_caption(
    caption = as_paragraph(
      "Table 1: ", as_i("Participant Data Listing")
    ),
    autonum = NULL
  ) %>%
  theme_vanilla() %>%
  autofit() %>%
  # conditional formatting for 'age'
  color(
    i = ~ age < 30, j = "age", color = "black", part = "body"
  ) %>%
  bg(
    i = ~ age < 30, j = "age", bg = "lightblue", part = "body"
  ) %>%
  bg(
    i = ~ age >= 30 & age < 50, j = "age", bg = "lightgreen", part = "body"
  ) %>%
  bg(
    i = ~ age >= 50 & age < 70, j = "age", bg = "yellow", part = "body"
  ) %>%
  bg(
    i = ~ age >= 70, j = "age", bg = "orange", part = "body"
  )

ft %>% 
  flex_style(width = 0.8)
}
```

# Data Visualization
```{r, fig.cap="Boxplot of Age Distribution"}
# Create a plotly plot of 
if(params$as_gt) {
plotly::plot_ly(
  data,
  x = ~sex,
  y = ~age,
  type = "box",
  color = ~sex,
  colors = c("lightblue", "pink")
) %>%
  layout(
    title = "Age Distribution by Sex",
    xaxis = list(title = "Sex"),
    yaxis = list(title = "Age (years)")
  )
}else{
  ggplot2::ggplot(data, aes(x = sex, y = age, fill = sex)) +
    geom_boxplot() +
    scale_fill_manual(values = c("Male" = "lightblue", "Female" = "pink")) +
    labs(
      title = "Age Distribution by Sex",
      x = "Sex",
      y = "Age (years)"
    ) +
    theme_minimal() +
    theme(legend.position = "none")
}


```

```{r, fig.cap="Heatmap of Age vs Blood Pressure"}
# bin ages and blood pressure
heat_data <- data %>%
  mutate(
    age_bin = cut(age, breaks = seq(20, 80, by = 10), include.lowest = TRUE, right = FALSE),
    bp_bin  = cut(blood_pressure, breaks = seq(80, 190, by = 20), include.lowest = TRUE, right = FALSE)
  ) %>%
  count(age_bin, bp_bin)

if(params$as_gt) {
# create heatmap
plot_ly(
  heat_data,
  x = ~age_bin,
  y = ~bp_bin,
  z = ~n,
  type = "heatmap",
  colors = colorRamp(c("white", "blue4"))
) %>%
  layout(
    title = "Heatmap of Age vs Blood Pressure",
    xaxis = list(title = "Age Group"),
    yaxis = list(title = "Blood Pressure Group (mmHg)")
  )
  
}else{
heat_data_clean <- heat_data %>% 
  filter(!is.na(age_bin), !is.na(bp_bin), !is.na(n))

ggplot(heat_data_clean, aes(x = age_bin, y = bp_bin, fill = n)) +
  geom_tile(color = "white") +
  scale_fill_gradient(low = "white", high = "blue4") +
  labs(
    title = "Heatmap of Age vs Blood Pressure",
    x = "Age Group",
    y = "Blood Pressure Group (mmHg)",
    fill = "Count"
  ) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1)
  )
}

```

**This report** was generated using `R Markdown`, *demonstrating the integration* of

- summary tables, 
- data listings, 
- interactive visualizations.
- another one 

# Show Code Chunk
```{r, echo=TRUE, include=FALSE}
# Example code chunk
head(data)

```

